.gitignore
third_party/proto/LICENSE
third_party/proto/README.google
third_party/proto/profile.proto

Proto imported from https://github.com/google/pprof

Add profile.proto and third party directory

---

ts/src/profilers/profile-serializer.ts
ts/test/profiles-for-tests.ts

Sample type for first value in heap profile was incorrect, so the profile could not be uploaded.
This change fixes that.

fix: change sample type for heap profile

---

package.json

move protobufjs from devDependecies to dependencies

---

ts/src/config.ts
ts/src/index.ts
ts/src/profiler.ts
ts/test/test-init-config.ts
ts/test/test-profiler.ts

don't send instance and zone if values not specified

---

package-lock.json
package.json

Reverts GoogleCloudPlatform/cloud-profiler-nodejs#60

Revert "build: add source-map-support for better stack traces"

---

ts/src/index.ts
ts/src/profiler.ts
ts/src/profilers/profile-serializer.ts
ts/test/test-profiler.ts

Using @return is correct style for nodejs.

fix: replace 'Returns' in comments with '@return'

---

ts/src/index.ts

Adds a function which can be used to collect profiles locally. This is intended for debugging.

feat: add way to profile locally

---

ts/src/config.ts

chore: document where log statements are printed

---

ts/src/config.ts
ts/src/index.ts
ts/test/test-init-config.ts

fix: set default log level to warn

---

package-lock.json
package.json

fix: remove clang-format dependency

---

js-green-licenses.json
package-lock.json
package.json

The `log-driver` package must be whitelisted, which is a dep of
`@google-cloud/common`.

chore: license check in posttest

---

ts/src/index.ts
ts/src/profilers/profile-serializer.ts
ts/test/profiles-for-tests.ts

fix: fix incorrect time profile duration

---

bindings/sampling-heap-profiler.cc

fix: use delete instead of free in sampling-heap-profiler.cc

---

package-lock.json
package.json

Release notes: https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/releases/edit/untagged-b424fc0140ffadf35280

chore: release 0.1.11

---

package-lock.json
package.json

Release notes: https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/releases/edit/untagged-cd08a2fb6182987090aa

chore: release 0.1.12

---

README.md

chore: clarify that logging is for diagnostic purposes

---

.circleci/config.yml
testing/README.md
testing/integration_test.go
testing/integration_test.sh

For previous discussion, see #132

feat: add test cases for integration test 

---

testing/kokoro/common.cfg
testing/kokoro/continuous.cfg
testing/kokoro/presubmit.cfg

Add kokoro configurations.
This is a step needed to enable integration tests.

chore: added kokoro configurations

---

testing/integration_test.go

This makes a few changes to further reduce verbosity, and will allow kokoro integration tests to pass again.

fix: fix e2e test

---

ts/src/index.ts
ts/src/profiler.ts
ts/src/profilers/heap-profiler.ts
ts/test/test-heap-profiler.ts
ts/test/test-init-config.ts
ts/test/test-profiler.ts

fix: start sampling heap profiler before any asynchronous calls

---

ts/src/profiler.ts
ts/test/test-profiler.ts

Reverts GoogleCloudPlatform/cloud-profiler-nodejs#196

Revert "chore: add language to profile labels"

---

ts/src/profiler.ts
ts/test/test-profiler.ts

chore: add language to deployment labels

---

bindings/time-profiler.cc

chore: stop using deprecated GetCpuProfiler() in node 10

---

package-lock.json
package.json
ts/src/index.ts
ts/src/profiler.ts
ts/src/profilers/time-profiler.ts
ts/src/v8-types.ts
ts/system-test/test-start.ts
ts/test/test-init-config.ts
ts/test/test-profiler.ts
ts/test/test-time-profiler.ts

Updates gts to ^0.6.0 and makes changes necessary for code to compile and pass tests after updating.

chore(deps): update dependency gts to ^0.6.0

---

package-lock.json
package.json

chore(package): update gts to version 0.7.1

---

bindings/time-profiler.cc

chore: remove SetIdle() function from CpuProfiler

---

package.json
testing/busybench/package.json
testing/busybench/src/busybench.ts
testing/busybench/tsconfig.json
testing/integration_test.go

fix: add modules needed to compile the profiler in typescript

---

package.json

Release notes:
https://github.com/googleapis/cloud-profiler-nodejs/releases/edit/untagged-0b0530f3a63747ba4268

release 0.2.2

---

README.md

cheapo fix for hacktoberfest2018

readme markdown fix

---

bindings/sampling-heap-profiler.cc
bindings/time-profiler.cc
package.json
testing/integration_test.go
testing/integration_test.sh

chore: enable v8 canary continuous tests

---

testing/integration_test.go

fix: fix compilation error in e2e tests

---

package.json

Reverts googleapis/cloud-profiler-nodejs#384

Revert "v0.3.0"

---

package.json
ts/src/profiler.ts

Manually tested to confirm that profiling agent still backs off as expected when many agents are running.

chore: update @google-cloud/common

---

tools/kokoro/continuous/common.cfg
tools/kokoro/presubmit/common.cfg
tools/kokoro/release/common.cfg

Finishes changes started in #407.
Also adds common configs to each directory with kokoro configs.

chore: finish separating kokoro configs into multiple directories

---

ts/test/test-init-config.ts
ts/test/test-profiler.ts

Should fix failing integration tests.

chore: update tests to be compatible with latest @types/sinon

---

ts/src/index.ts
ts/test/test-init-config.ts

feat: support Knative environment variables for service and version

---

CHANGELOG.md
package.json

Release @google-cloud/profiler v1.1.2

---

CHANGELOG.md
package.json

Release @google-cloud/profiler v2.0.0

---

ts/src/index.ts
ts/test/test-init-config.ts

fix: agent should correctly set zone in GCP

---

CHANGELOG.md
package.json

Release @google-cloud/profiler v2.0.1

---

CHANGELOG.md
package.json

Release @google-cloud/profiler v2.0.2

---

CHANGELOG.md
package.json

chore: release @google-cloud/profiler v3.0.0

---

.github/workflows/ci.yaml

Tested: Pushed this change to my fork, and tests passed
https://github.com/nolanmar511/cloud-profiler-nodejs/actions/runs/79322579

chore: run golint checks in GitHub action

---

.github/workflows/ci.yaml

Tested:
All tests passed on my fork: https://github.com/nolanmar511/cloud-profiler-nodejs/actions/runs/79344099

chore: run system tests in GitHub workflow

---

system-test/integration_test.sh

chore: add backoff to retry function used in e2e test
