googleapis/cloud-profiler-nodejs

- lib/heap_builder.js
Unsampling has been moved into V8 with
https://codereview.chromium.org/1706343002 so this logic is no longer
necessary in the agent.
This change also updates the units used for emitted profiles to be more
consistent with other profilers.
> Remove unsampling logic from agent

- package.json
Coverage reporting regressed by #29 which added build/ to nyc.exclude
configuration.
> fix: remove build/ from nyc exclude

- package.json
- proto/profiler.d.ts
- proto/profiler.js
Now that we have `profiler.proto` imported, add rules for, and generate JS and type definitions from the proto.
> chore: generate js/d.ts from profiler.proto

- package-lock.json
- package.json
- ts/src/profilers/profile-serializer.ts
TypeScript 2.6 makes type checking for functions stricter [1]. Instead
of using bivariant types for functions parameters, TypeScript now uses
contravaiance.
This has been breaking our CI with Node 6 ([example](https://travis-ci.org/GoogleCloudPlatform/cloud-profiler-nodejs/jobs/295479690)) as it doesn't use the locked down version of typescript as specified by our `package-lock.json`. Let's bite the bullet and upgrade to TypeScript 2.6.
[1] https://blogs.msdn.microsoft.com/typescript/2017/10/31/announcing-typescript-2-6/
/cc @matthewloring in case he has ideas on how to avoid the cast to `Array<T>` for the `children` array.
> fix: add support for TypeScript 2.6

- package.json
TypeScript famously doesn't follow semver. To avoid unnecessary
breakages in CI due, let's use a stricter semver range.
> chore: use stricter semver range for typescript

- package.json
Including tests in code coverage report seems to be inflating the overall code coverage.
I feel that this makes the code coverage report misleading, so tests should not be included in code coverage.
> fix: ignore build/test in test coverage

- ts/src/profilers/profile-serializer.ts
- ts/src/v8-types.ts
- ts/test/profiles-for-tests.ts
- ts/test/test-profile-serializer.ts
This is a regression from #34.
If no function name is specified, the function name should be recorded as  '(anonymous)' .
> fix: should use '(anonymous)' as function name when no name specified

- .gitignore
- package.json
After #52, npm package did not include src files and code coverage of tests was added back to code coverage.
This change fixes that.
> add out/src to files

- ts/src/profiler.ts
The Buffer constructor is deprecated. It was unnecessary anyway as the
value returned by `finish` is a Buffer anyway.
> fix: avoid unnecessary deprecated buffer constructor

- package-lock.json
- package.json
This gives us ts source files rather than output js files in the stacktraces. Example:
```
at Object.<anonymous> (ts/test/test-profiler.ts:97:17)
at step (out/test/test-profiler.js:47:23)
at Object.next (out/test/test-profiler.js:28:53)
at fulfilled (out/test/test-profiler.js:19:58)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
```
vs 
```
at Object.<anonymous> (out/test/test-profiler.js:124:32)
at step (out/test/test-profiler.js:47:23)
at Object.next (out/test/test-profiler.js:28:53)
at fulfilled (out/test/test-profiler.js:19:58)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
```
> build: add source-map-support for better stack traces

- ts/src/profiler.ts
- ts/test/test-profiler.ts
Fixes #70 
I tested by running 8 copies of the acmeAir app both before and after this change (for about 10 minutes). Before, ESOCKETTIMEDOUT errors occurred on every request to createProfile(), after, no ESOCKETTIMEDOUT errors were observed.
> fix: fix ESOCKETTIMEDOUT Error by increasing timeout to 1 hour for createProfile()

- ts/src/profiler.ts
- ts/test/test-profiler.ts
Right now, duration is a required field of RequestProfile. This does not make sense because heap profiles do not need to have a duration.
Prior to this change, when attempting to collect heap profiles, the following error would occur:
```
Error collecting and uploading profile: ApiError: Request contains an invalid argument
```
> fix: make duration in RequestProfile optional, so Heap Profiles do not have to have durations

- package-lock.json
- package.json
This gets rid of the deprecation warnings when building with node 9.
CXX(target) Release/obj.target/sampling_heap_profiler/bindings/sampling-heap-profiler.o
In file included from ../bindings/sampling-heap-profiler.cc:18:
In file included from ../node_modules/nan/nan.h:192:
../node_modules/nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
> chore: upgrade nan dependency

- package-lock.json
- package.json
- ts/src/config.ts
- ts/src/profiler.ts
- ts/test/test-init-config.ts
- ts/test/test-profiler.ts
- ts/third_party/types/README.google
- ts/third_party/types/common-types.ts
Fixes #43 and #44.
See #56 for previous discussion on this topic.
> feat: add exponential and server-mediated backoff on retries

- package-lock.json
- package.json
- ts/src/profiler.ts
- ts/test/test-profiler.ts
fixes: #68 
Tests with source mapping has previously failed when Math.random() was stubbed with sinon. This adds source-mapping back and modifies code so that Math.random() does not need to be stubbed.
> feat: add source mapping to tests for better stack traces

- package.json
- ts/src/index.ts
Greenkeeper's PR #104 for updating @types/node to 9.3.0 has failing tests. 
This change updates @types/node and modified code so tests continue to pass (specifically ts/src/index.ts has a change).
> chore: Update @types/node to the latest version

- package.json
Reverts GoogleCloudPlatform/cloud-profiler-nodejs#124
After making this change, the projectId is not retrieved from the environment variable on GCE.
I will update this dependency more carefully in a separate PR.
> Revert "Update @google-cloud/common to the latest version 🚀"

- package-lock.json
- ts/src/config.ts
- ts/src/profiler.ts
- ts/test/test-init-config.ts
- ts/test/test-profiler.ts
It's useful when testing the agent to be able to upload profiles to the test API.
This PR adds a field to the config, `baseApiUrl`, which a user can use to set the api url used to something other than `cloudprofiler.googleapis.com`.
> feat: add field to config so user can use test API

- package-lock.json
- package.json
- ts/src/index.ts
- ts/test/test-init-config.ts
Updates gcp-metadata to version 0.5.0.
Also makes the changes so that code uses gcp-metadata's new API.
In addition to running the tests, I also ran a trivial application in GCE and saw that the zone was set in the profiles after this update.
> chore: update gcp-metadata

- package-lock.json
- package.json
- ts/src/index.ts
This PR adds `engines` to the package.json and prevents the profiler from starting when a version of node not matching the version specified in `engines` is used.
> fix: don't run profiler if incompatible version of node is used

- testing/busybench.js
We need to use this benchmark for other testing of the agent, so are adding it before the rest of the integration test.
> chore: add benchmark which will be used for e2e testing

- testing/busybench.js
- testing/integration_test.go
- testing/integration_test.sh
This PR includes small changes needed to allow e2e tests to run successfully. 
Most notably, it stops using `fill()` in busybench.js -- based on profiles, it appears that `fill()` now uses a setImmediate somewhere in node 8 and node 9, so the work was no longer attributed to `benchmark()`.
> fix: update integration test so it runs successfully.

- testing/busybench.js
- testing/integration_test.go
The buffer wasn't showing up too much in the heap profiles, so the integration test didn't always find the `benchmark()` function.
With this change, the benchmark() function dominates memory allocations.
> fix: modify benchmark so that it fills arrays, rather than a buffer

- package.json
> fix: common-types should be part of package

- testing/integration_test.sh
Will stop the lines below form appearing in integration test's output:
```
+ '[176' == ']'
github/cloud-profiler-nodejs/testing/integration_test.sh: line 28: [176: command not found
```
> fix: make fix to integration_test.sh

- ts/src/profiler.ts
- ts/test/test-profiler.ts
Fixes #196 
This change also removes some unused variables from `test-profiler.ts`.
> chore: add language to profile labels

- .circleci/config.yml
- package-lock.json
Running `npm audit` revealed that the module versions in the package-lock.json did not satisfy versions in `package.json`.
This should fix #207.
> chore: update package-lock.json

- package-lock.json
- package.json
Closes #218 
Updates to latest version of nyc, and updates package-lock.json.
> chore: update nyc to the latest version

- ts/src/index.ts
> fix: coerce node version so pre, nightly, alpha, and beta versions of node can be used with profiler.

- testing/integration_test.go
> chore: use --trace-warnings flag when calling node in e2e test

- package-lock.json
- package.json
- ts/src/profiler.ts
- ts/test/test-profiler.ts
> fix: parse the response body message to determine retry backoff

- package-lock.json
- ts/src/config.ts
- ts/src/profilers/heap-profiler.ts
- ts/src/profilers/profile-serializer.ts
- ts/test/profiles-for-tests.ts
- ts/test/test-heap-profiler.ts
- ts/test/test-init-config.ts
- ts/test/test-profiler.ts
This shows the diff between profiles collected before and after this change. These profiles are on the project nolanmar-test-1 (which I think I've added aalexand and ofrobots to as viewers -- let me know if this isn't the case).
Fixes #205
> feat: hide samples with path containing @google-cloud/profiler by default

- .circleci/config.yml
Since #267, the npm audit check has been failing since there is not package-lock.json.
The PR modifies the npm audit presubmit test so a package-lock.json is generated before npm audit is run.
> chore: generate package-lock.json in npm-audit presubmit check

- package.json
- ts/src/index.ts
- ts/src/profiler.ts
This is necessary to upgrade `@google-cloud/common` to 0.21.0.
Logging was a part of common previously, but has been moved (more details on https://github.com/googleapis/nodejs-common/issues/204)
> chore: use console-log-level for logging

- package.json
Fixes #276.
After this, it will still be necessary to upgrade the version delay which is being used.
> fix: use fixed minor version of delay

- ts/test/test-init-config.ts
> fix: modify so tests pass when GCLOUD_PROJECT specified

- package.json
- ts/src/index.ts
- ts/src/profilers/time-profiler.ts
- ts/system-test/test-start.ts
- ts/test/test-heap-profiler.ts
- ts/test/test-time-profiler.ts
The package started shipping types as part of the official package.
These are breaking changes w.r.t previous `@types/delay` types. We need
to import the module differently now for things to work correctly.
> chore(package): upgrade to delay@3.1.0

- package.json
- ts/src/config.ts
- ts/src/index.ts
- ts/src/profiler.ts
- ts/src/profilers/heap-profiler.ts
- ts/system-test/test-start.ts
- ts/test/profiles-for-tests.ts
- ts/test/test-heap-profiler.ts
- ts/test/test-init-config.ts
- ts/test/test-profiler.ts
Breaking changes in common: common was split in multiple modules, HTTP
dependency must be passed in by client library.
Fixes: https://github.com/googleapis/nodejs-common/issues/204
Fixes: https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/pull/266
> fix(deps): update dependency @google-cloud/common to ^0.23.0

- package.json
- ts/src/profiler.ts
- ts/system-test/test-start.ts
Use teeny-request instead of large `request` dependency. According to
[require-so-slow](https://www.npmjs.com/package/require-so-slow),
load time improves from 1500 ms to 600 ms.
Before with `request`:
After with `teeny-request`:
> feat: use smaller HTTP dependency

- ts/src/profiler.ts
When an error occurs when collecting a profile, right now, the status message of the response is logged at the debug level.
This change makes it so the response body's message is logged instead when possible, hopefully making the debug logs clearer.
> chore: use response body message as error message when possible

- ts/src/index.ts
- ts/test/fixtures/test-config.json
- ts/test/test-init-config.ts
fixes #309 
Without this fix, profiler continue to try to create profiles, logging failures to create the profile at the "warn" level.
> feat: validate service name before profiler creation

- bindings/sampling-heap-profiler.cc
- bindings/time-profiler.cc
I confirmed that this still builds with Node 10.0.0.
Part of fixing #315
> chore: stop using methods with deprecation warnings in node 10.12.0

- samples/app.js
- samples/snippets.js
The documentation on https://cloud.google.com/profiler/docs/profiling-nodejs
should come from code snippets on GitHub rather than be hard coded.
We show JS snippets, so I can't use the TS sources.
> Add samples with snippets for documentation

- testing/integration_test.go
> busybench.ts requires profiler itself, do not  --require on command line

- binding.gyp
- bindings/profiler.cc
- package.json
Module name is used in node-pre-gyp's flags. This name should be more unique.
> chore: rename node-pre-gyp module

- testing/integration_test.go
Log for v8 canary test run with this change: https://sponge.corp.google.com/target?id=579e6989-4c99-43fd-b719-58442c00cbf7&target=cloud-profiler%2Fnodejs-agent%2Fpresubmit&searchFor=
> fix: use NAN from github to fix v8 canary e2e test

- tools/linux_build_and_test.sh
For our continuous e2e tests, the value of $KOKORO_JOB_TYP is CONTINUOUS_INTEGRATION not CONTINUOUS_GITHUB.
This change should fix continuous e2e tests which were broken with #357.
> fix: fix continuous e2e test

- tools/kokoro/common.cfg
- tools/kokoro/continuous-v8-canary.cfg
- tools/kokoro/continuous.cfg
- tools/kokoro/presubmit.cfg
I'm going to add a kokoro release build. I'd like to have this config placed in the same directory as other configs. So, since it will be less clear if we have the release config in the "testing" directory, I plan to move all configs to the "tools" directory.
After this PR is merged, I will change the directory which internal configs point to. Then I will delete the configs in the original location.
> chore: add copy of kokoro configs to tools/kokoro

- README.md
The word 'reccomended' is not spelled correctly.
> fix: minor spelling mistake

- tools/kokoro/continuous/continuous-v8-canary.cfg
- tools/kokoro/continuous/continuous.cfg
- tools/kokoro/presubmit/presubmit.cfg
This is the first step to moving the presubmit and continuous configs into their own directories.
> chore: copy continuous and presubmit kokoro configs into separate directories

- tools/kokoro/release/publish-npm.cfg
- tools/linux_build_and_test.sh
In experimenting with the kokoro release, I found I that there are some errors in current kokoro configs and scripts used.
Right now, we want to call the publish script directly (rather than use devrel's trampoline.sh, which we aren't currently set up to do anyways). Also the release workflow did not copy binaries to "gs://cloud-profiler/nodejs/release".
> fix: correct errors in kokoro release

- tools/kokoro/release/publish-npm.cfg
The keys to publish to npm have been updated to transition to per-project keys. 
We need to update he name of the key we used.
> fix: update name of key to publish to npm

- tools/publish.sh
We are not yet using gcp-releasetool, and currently get the following error when trying to install this with pip: 
```
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/releasetool'
```
We should remove these steps (at least until we unify our release process with the release process for other Google Client Library node modules).
Part of #47
> chore: don't install gcp-releasetool in publish script

- tools/publish.sh
In #417, I updated the the npm token fetched from keystore. I did not update the name of the token in the publish script.
This is part of #47.
> fix: update npm token used in publish script

- tools/kokoro/release/publish-npm.cfg
- tools/publish.sh
I sync'ed with jkwlui, and the old npm token had been deleted unintentionally. The new per-project npm tokens are not yet ready to be used. So we should publish using the original token (which is once again available).
We also need to install node onto the kokoro VM.
> fix: fix script for publishing to npm

- binding.gyp
https://github.com/nodejs/nan/issues/807#issuecomment-455750192 recommends using the "-Wno-cast-function-type" to silence deprecations warnings that appear with GCC 8.
Silences warnings users see in #315.
> chore: silence deprecation warnings that appear with gcc 8

- binding.gyp
> chore: add comment to explain suppressed compilation warnings

- .kokoro/test.sh
Currently, code coverage is not run. This is the error we see:
```
+ '[' false -ne true ']'
github/cloud-profiler-nodejs/.kokoro/test.sh: line 42: [: false: integer expression expected
```
> fix: fix testing bash script so code coverage reported

- testing/integration_test.go
This allows v8-canary e2e tests to pass. 
Example: https://sponge.corp.google.com/target?id=364d9f26-a6a0-41d4-b75b-cec020b84abc&target=cloud-profiler%2Fnodejs-agent%2Fcontinuous%2Fcontinuous-v8-canary&searchFor=
> fix: use latest version of nan when installing pprof-nodejs in v8-canary test

- ts/src/profiler.ts
When running a benchmark in docker, Jianqiao saw this error:
```
@google-cloud/profiler Failed to initialize source maps and start profiler: Error: failed to get source maps from /: Error: ENOENT: no such file or directory, lstat 
```
Lazy source map loading will likely change this, but as a work-around for now, I don't think failure to initialize the SourceMapper should disabled the profiler.
> fix: profiler should still start when source mapper can't be initialized

- .circleci/config.yml
Reverts googleapis/cloud-profiler-nodejs#446
> chore: Revert "fix: temporarily don't npmaudit check to pass before release"

- README.md
This is consistent with the Node.JS [Trace Agent's](https://github.com/googleapis/cloud-trace-nodejs) banner.
> docs: Switch from alpha to beta banner

- testing/integration_test.go
TESTED: Confirmed output from nvm install for presubmit system test appeared in GCP logging console.
> chore: redirect some test output to serial port 3

- package.json
- ts/src/config.ts
- ts/src/index.ts
- ts/src/logger.ts
- ts/src/profiler.ts
- ts/system-test/test-start.ts
- ts/test/profiles-for-tests.ts
- ts/test/test-init-config.ts
- ts/test/test-profiler.ts
Also ran `npm run fix` , and fixed indicated errors.
> chore(deps): update dependency gts to v1

- ts/src/profiler.ts
Note that the version of the agent will only be logged if the configuration is successfully initialized, and the "start()" method of the Profiler class is called.
> chore: log the agent's version on start-up

- package.json
Reverts googleapis/cloud-profiler-nodejs#534
Our E2E tests started failing with compilation errors; I think it's related to this change.
> Revert "chore(deps): update dependency nock to v11"

- package.json
`@google-cloud/profiler` depends heavily on the `pprof` module. 
We want to be sure that changes to `pprof` that introduce bugs or problems in `@google-cloud/profiler` can be caught by `@google-cloud/profiler`'s  presubmit tests, rather than immediately impacting `@google-cloud/profiler` as its running in prod. 
This will allow us to concentrate testing in this repository, rather than duplicate all testing here and in https://github.com/google/pprof-nodejs.
> chore(deps): pin pprof 

- .circleci/config.yml
We publish using Kokoro now. This workflow no longer works.
> chore: remove circleci publish_npm workflow

- system-test/integration_test.go
- system-test/integration_test.sh
Our E2E test is broken, because it depends on google.golang.org/api/compute/v1,  which depends on google.golang.org/api/option, which is currently broken for all users who are not using go modules (https://github.com/googleapis/google-api-go-client/issues/441).
This should allow our E2E test to pass again.
> chore: use go modules in integration test

- README.md
- system-test/integration_test.go
This library did work with Node 12 prior to this change.
This change documents Node 12 support, and starts running integration tests with node 12.
> feat: add support for Node 12

- synth.py
we shouldn't overwrite `.github/workflows/ci.yaml` with the template version, since `cloud-profiler-nodejs` has custom checks.
see: https://github.com/googleapis/cloud-profiler-nodejs/pull/631
> build: allow profiler to have custom actions

- system-test/integration_test.sh
This allows the installation of dependencies for golang test to be retried.
> chore: compile then run golang test in e2e test

- tsconfig.json
#640 introduces automatic `gts clean` on `precompile`. `gts` depends on `tsconfig.json`, which is currently malformed due to trailing `,`. This PR fixes this problem and will allow builds from #640 to finish.
> fix: malformed tsconfig causing broken tests #640
